---

- name: instal | Get samson from git
  git:
    repo="{{ samson_git_url }}"
    dest="{{ samson_deploy_dir }}"
    force="no"
    version="{{ samson_version | default('omit') }}"
    accept_hostkey=true
  become_user: "{{ samson_user }}"
  notify:
    - restart samson

- name: instal | Install Package.json
  npm:
    path="{{ samson_deploy_dir }}"
    state="present"
  notify:
    - restart samson

- name: Run bundler
  bundler:
    chdir="{{ samson_deploy_dir }}"
    exclude_groups="{{ samson_exclude_groups }}"
  notify:
    - restart samson

- name: instal | Deploy ENV config
  template:
    src="env.j2"
    dest="{{ samson_deploy_dir }}/.env"
    owner="{{ samson_user }}"
    group="{{ samson_group }}"
    mode=0600
  notify:
    - restart samson
