---


- name: Install common dependencies
  apt:
    name="{{ item }}"
  with_items: "{{ samson_apt_dependecies }}"

- name : Create samson group
  group: 
    name="{{ samson_group }}"

- name : Create samson user
  user : 
    name="{{ samson_user }}"
    group="{{ samson_group }}"
    shell="/sbin/nologin"
    home="{{ samson_home_dir }}"
    createhome="yes"

- name: Create samson directories
  file: 
    path="{{ samson_home_dir }}"
    owner="{{ samson_user }}"
    group="{{ samson_group }}"
    mode=0755
    state=directory
  with_items: 
    - "{{ samson_home_dir }}"
    - "{{ samson_log_dir }}"

- name: Get samson from git
  git:
    repo="{{ samson_git_url }}"
    dest="{{ samson_deploy_dir }}"
    force="no"
    version="{{ samson_version | default('omit') }}"
    accept_hostkey=true
  become_user: "{{ samson_user }}"

- name: Install Package.json
  npm:
    path="{{ samson_deploy_dir }}"
    state="present"

- name: Run bundler
  bundler:
    chdir="{{ samson_deploy_dir }}"
    exclude_groups="{{ samson_exclude_groups }}"
