---


- name: Install common dependencies
  apt:
    name="{{ item }}"
  with_items: "{{ samson_apt_dependecies }}"

- name : Create samson group
  group: 
    name="{{ samson_group }}"
  notify:
    - restart samson

- name : Create samson user
  user : 
    name="{{ samson_user }}"
    group="{{ samson_group }}"
    shell="/bin/bash"
    home="{{ samson_home_dir }}"
    createhome="yes"
  notify:
    - restart samson

- name: Create samson directories
  file: 
    path="{{ item }}"
    owner="{{ samson_user }}"
    group="{{ samson_group }}"
    mode=0755
    state=directory
  with_items: 
    - "{{ samson_home_dir }}"
    - "{{ samson_log_dir }}"
  notify:
    - restart samson

- name: Include install yaml
  include: Install.yml

- name: Include configuration yaml
  include: configuration.yml

- name: Flush handlers
  meta: flush_handlers

- name: Ensure Samson is running
  service:
    name="samson"
    state="started"
    enabled=True
